// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LocationModelExample",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "LocationModelExample",
            targets: ["AppModule"],
            bundleIdentifier: "com.kokiTakashiki.LocationModelExample",
            teamIdentifier: "GY636G2259",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LocationModel", package: "locationmodel")
            ],
            path: "."
        )
    ]
)
